version: '3'

services:
  master:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8089:8089"
    env_file:
      - .env/.env.vertica/.env.prod
    volumes:
      - .:/vertica
    command:
      -f /vertica/test_vertica.py --master -H http://master:8089
  
  worker:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env/.env.vertica/.env.prod   
    volumes:
      - .:/vertica
    command: 
      -f /vertica/test_vertica.py --worker --master-host master

  vertica_db:
    image: jbfavre/vertica:latest
    ports:
      - "5433:5433"
    env_file:
      - .env/.env.db/.env.prod
    volumes:
      - .:/vertica