version: '3'
services:
  ugc_service:
    build: ugc-service
    env_file:
      - ugc-service/.env/.env.prod
    expose:
      - "8000"
    restart: always
    depends_on:
      - kafka_broker
      - zookeeper
    networks:
      - cinema_backend_network

  movies_etl_service:
    build: movies-etl-service
    env_file:
      - movies-etl-service/.env/.env.prod
    restart: always
    depends_on:
      - elasticsearch
    networks:
      - cinema_backend_network

  ugc_etl_service:
    build: ugc-etl-service
    env_file:
      - ugc-etl-service/.env/.env.prod
    expose:
      - "8000"
    restart: always
    depends_on:
      - kafka_broker
      - clickhouse-node1

  data_faker_service:
    build: data-faker-service
    env_file:
      - data-faker-service/.env/.env.prod
    depends_on:
      - movies_postgres
      - admin_service
    networks:
      - cinema_backend_network

  asyncapi_service:
    build: asyncapi-service
    env_file:
      - asyncapi-service/.env/.env.prod
    expose:
      - "8000"
    restart: always
    depends_on:
      - movies_redis
      - elasticsearch
    networks:
      - cinema_backend_network

  admin_service:
    build: admin-service
    env_file:
      - admin-service/.env/.env.prod
    expose:
      - "8000"
    restart: always
    volumes:
      - cinema_backend_static
    depends_on:
      - movies_postgres
    networks:
      - cinema_backend_network

  authapi_service:
    build: authapi-service
    env_file:
      - authapi-service/.env/.env.prod
    expose:
      - "8000"
    restart: always
    depends_on:
      - auth_postgres
      - auth_redis
    networks:
      - cinema_backend_network

  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one:1.7
    expose:
      - "6831"
      - "5778"
      - "16686"
      - "14250"
      - "14268"
      - "14269"
    networks:
      - cinema_backend_network

  clickhouse-node1:
    image: yandex/clickhouse-server:20.4
    container_name: clickhouse-node1
    hostname: clickhouse-node1
    expose:
      - "8123"
      - "9000"
    volumes:
      - ./clickhouse-data/node1:/etc/clickhouse-server
    depends_on:
      - zookeeper
    networks:
      - cinema_backend_network

  clickhouse-node2:
    image: yandex/clickhouse-server:20.4
    container_name: clickhouse-node2
    hostname: clickhouse-node2
    volumes:
      - ./clickhouse-data/node2:/etc/clickhouse-server
    depends_on:
      - zookeeper
    networks:
      - cinema_backend_network

  clickhouse-node3:
    image: yandex/clickhouse-server:20.4
    container_name: clickhouse-node3
    hostname: clickhouse-node3
    volumes:
      - ./clickhouse-data/node3:/etc/clickhouse-server
    depends_on:
      - zookeeper
    networks:
      - cinema_backend_network

  clickhouse-node4:
    image: yandex/clickhouse-server:20.4
    container_name: clickhouse-node4
    hostname: clickhouse-node4
    volumes:
      - ./clickhouse-data/node4:/etc/clickhouse-server
    depends_on:
      - zookeeper
    networks:
      - cinema_backend_network

  kafka_broker:
    image: confluentinc/cp-kafka:7.0.1
    expose:
      - "9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka_broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    networks:
      - cinema_backend_network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - cinema_backend_network

  movies_postgres:
    image: postgres:13
    env_file:
      - docker/movies_postgresql/.env/.env.prod
    expose:
      - "5432"
    restart: always
    volumes:
      - ./docker/movies_postgresql/init_scripts:/docker-entrypoint-initdb.d
      - cinema_backend_movies_pg_data
    networks:
      - cinema_backend_network

  auth_postgres:
    image: postgres:13
    env_file:
      - docker/auth_postgresql/.env/.env.prod
    expose:
      - "5432"
    restart: always
    volumes:
      - ./docker/auth_postgresql/init_scripts:/docker-entrypoint-initdb.d
      - cinema_backend_auth_pg_data
    networks:
      - cinema_backend_network

  elasticsearch:
    image: elasticsearch:7.17.5
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    expose:
      - "9200"
    restart: always
    volumes:
      - cinema_backend_elasticsearch_data
    networks:
      - cinema_backend_network

  movies_redis:
    image: redis:7.0.4-alpine
    expose:
      - "6379"
    restart: always
    networks:
      - cinema_backend_network

  auth_redis:
    image: redis:7.0.4-alpine
    expose:
      - "6379"
    restart: always
    networks:
      - cinema_backend_network

  ugc_redis:
    image: redis:7.0.4-alpine
    expose:
      - "6379"
    restart: always
    networks:
      - cinema_backend_network

  ugc_extra_redis:
    image: redis:7.0.4-alpine
    expose:
      - "6379"
    restart: always
    networks:
      - cinema_backend_network

  ugc_mongodb:
    image: mongo
    expose:
      - "27017"
    restart: always
    networks:
      - cinema_backend_network

  nginx:
    image: nginx:latest
    volumes:
      - cinema_backend_static
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/configs:/etc/nginx/conf.d
    expose:
      - "80"
    restart: always
    ports:
      - "80:80"
    depends_on:
      - admin_service
      - asyncapi_service
      - authapi_service
    networks:
      - cinema_backend_network

volumes:
  cinema_backend_auth_pg_data:
  cinema_backend_movies_pg_data:
  cinema_backend_elasticsearch_data:
  cinema_backend_static:

networks:
  cinema_backend_network:
    driver: bridge