version: '3'
services:
  etl_app:
    build: etl
    env_file:
      - etl/.env/.env.prod
    restart: always
    depends_on:
      - elasticsearch
    networks:
      - docker_compose_sprint4_network

  data_faker:
    build: data-faker
    env_file:
      - data-faker/.env/.env.prod
    depends_on:
      - postgres
      - admin-service
    networks:
      - docker_compose_sprint4_network

  postgres:
    image: postgres:13
    env_file:
      - postgresql/.env/.env.prod
    expose:
      - "5432"
    restart: always
    volumes:
      - ./postgresql/init_scripts:/docker-entrypoint-initdb.d
      - sprint4_pg_data:/var/lib/postgresql/data
    networks:
      - docker_compose_sprint4_network

  elasticsearch:
    image: elasticsearch:7.17.5
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    expose:
      - "9200"
    restart: always
    volumes:
      - sprint4_elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - docker_compose_sprint4_network

  redis:
    image: redis:7.0.4-alpine
    expose:
      - "6379"
    restart: always
    networks:
      - docker_compose_sprint4_network

  nginx:
    image: nginx:latest
    volumes:
      - sprint4_static:/static/:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/configs:/etc/nginx/conf.d
    expose:
      - "80"
    restart: always
    ports:
      - "80:80"
    depends_on:
      - admin-service
      - api
    networks:
      - docker_compose_sprint4_network

  api:
    build: fastapi
    env_file:
      - fastapi/.env/.env.prod
    expose:
      - "8000"
    restart: always
    depends_on:
      - redis
      - elasticsearch
    networks:
      - docker_compose_sprint4_network

  admin-service:
    build: admin-service
    env_file:
      - admin-service/.env/.env.prod
    expose:
      - "8000"
    restart: always
    volumes:
      - sprint4_static:/opt/app/src/static/
    depends_on:
      - postgres
    networks:
      - docker_compose_sprint4_network

volumes:
  sprint4_pg_data:
  sprint4_elasticsearch_data:
  sprint4_static:

networks:
  docker_compose_sprint4_network:
    driver: bridge