# Generated by Django 3.2 on 2022-07-05 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_alter_models_fix_null_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personfilmwork',
            name='role',
            field=models.TextField(choices=[('actor', 'actor'), ('writer', 'writer'), ('director', 'director')],
                                   verbose_name='role'),
        ),
    ]
