name: Static flake8 code checking
on: push
jobs:
  linter_async_service:
    name: Linter
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Python setting up
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.0
    - name: Installing dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8==5.0.4
        pip install flake8-print==5.0.0
    - name: Flake8 asyncapi
      run: flake8 asyncapi-service
    - name: Flake8 authapi
      run: flake8 authapi-service