name: Static flake8 and Mypy code checking
on: 
  push:
  pull_request:
    branches: [ master ]
jobs:
  tests:
    name: Code checking
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Installing dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        pip install flake8-print
        pip install flake8-bugbear
        pip install flake8-simplify
        pip install flake8-pie
        pip install flake8-commas
        pip install flake8-comprehensions
        pip install flake8-eradicate
        pip install flake8-quotes
        pip install flake8-variables-names
        pip install dlint
        pip install mypy
        pip install motor-stubs
        pip install orjson
    - name: Flake8
      run: |
        flake8 ugc-extra-service --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 ugc-extra-service --count --exit-zero --statistics
    - name: Mypy
      run: mypy ugc-extra-service/src
  notification:
    name: Telegram notification
    needs: tests
    runs-on: ubuntu-latest
    steps:
    - name: Telegram notification
      uses: appleboy/telegram-action@master
      with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          args: Checks ${{ github.run_id }} was successful
