name: Проверка кода flake8
on: push
jobs:
  linter_async_service:
    name: Линтер AsyncAPI
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Установка Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.0
    - name: Установка зависимостей
      run: |
        python -m pip install --upgrade pip
        pip install flake8==5.0.4
    - name: Flake8
      run: flake8 asyncapi-service

  linter_auth_service:
    name: Линтер AuthAPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Установка Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.0
      - name: Установка зависимостей
        run: |
          python -m pip install --upgrade pip
          pip install flake8==5.0.4
      - name: Flake8
        run: flake8 authapi-service