name: Static flake8 code checking
on: push
jobs:
  linter_async_service:
    name: Linter
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Python setting up
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Installing dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        pip install flake8-print
        pip install flake8-bugbear
        pip install flake8-simplify
        pip install flake8-pie
        pip install flake8-commas
        pip install flake8-comprehensions
        pip install flake8-eradicate
        pip install flake8-quotes
        pip install flake8-variables-names
        pip install dlint
        pip install mypy
        pip install uvicorn-stubs
    - name: Flake8 asyncapi
      run: flake8 asyncapi-service
    - name: Flake8 authapi
      run: flake8 authapi-service
    - name: Flake8 ugc
      run: flake8 ugc-service
    - name: Flake8 ugc-etl
      run: flake8 ugc-etl-service
    - name: Flake8 ugc-extra
      run: flake8 ugc-extra-service
    - name: mypy ugc-extra
      run: mypy ugc-extra-service