name: Static flake8 and Mypy code checking
on: 
  push:
  pull_request:
    branches: [ master ]
jobs:
  tests:
    name: Code checking
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
        service: ["notifications-worker-service", "notifications-service"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Installing dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        cd ${{ matrix.service }}
        poetry config virtualenvs.create false
        poetry install
    - name: Flake8
      run: |
        flake8 ${{ matrix.service }}/src --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 ${{ matrix.service }}/src --count --exit-zero --statistics
    - name: Mypy
      run: mypy --python-version=${{ matrix.python-version }} ${{ matrix.service }}/src
  notification:
    name: Telegram notification
    needs: tests
    runs-on: ubuntu-latest
    steps:
    - name: Telegram notification
      uses: appleboy/telegram-action@master
      with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          args: Checks ${{ github.run_id }} in ${{ github.repository }} by ${{ github.actor }} was successful!
